### ISSUE TITLE
~/.caper/default.conf file isn't created after caper init

### ISSUE THREAD

**Issue by xinmiaoyan** [ENCODE-DCC/caper#130]
I've installed caper v=1.6.3 on my seadragon cluster, and after I've try caper init seadragon, it shows:
```
Traceback (most recent call last):
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/bin/caper", line 13, in <module>
    main()
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/cli.py", line 672, in main
    init_caper_conf(parsed_args.conf, parsed_args.platform)
  File "/rsrch3/home/genomic_med/xyan4/.conda/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper_init.py", line 176, in init_caper_conf
    raise ValueError('Unsupported backend {p}'.format(p=backend))
ValueError: Unsupported backend seadragon
```
how to deal with this problem? really appreciate your response.

**Comment by leepc12** [comment]
`seadragon` is not a supported backend. Please check README for supported backends (e.g. sge, slurm, gcp, aws, ...)
