### ISSUE TITLE
cannot run caper

### ISSUE THREAD

**Issue by yinshiyi** [ENCODE-DCC/caper#14]
Traceback (most recent call last):
  File "/home/sxx128/caper/bin/caper", line 11, in <module>
    from caper.caper import main
  File "/home/sxx128/caper/bin/../caper/caper.py", line 18, in <module>
    from pyhocon import ConfigFactory, HOCONConverter
ModuleNotFoundError: No module named 'pyhocon'

**Comment by leepc12** [comment]
It looks like you don't have python3? Please try `pip install pyhocon`.

**Comment by yinshiyi** [comment]
thanks, problem solved smooth as butter
