### ISSUE TITLE
UnboundLocalError: local variable 'p' referenced before assignment

### ISSUE THREAD

**Issue by Al-Murphy** [ENCODE-DCC/caper#160]
My apologies if this is a trivial issue but I have followed the steps in the README but am getting the following error when running the pipeline on mouse H3K4me3 data (running on base environment with caper version 2.1.3):

```
$ caper run chip-seq-pipeline2/chip.wdl -i germ_BXD100_tr.json --conda
2022-02-09 14:46:26,219|caper.cli|INFO| Cromwell stdout: /shared/aemurphy/H3K4me3_mouse_baker_2019/cromwell.out.1
2022-02-09 14:46:26,254|caper.caper_base|INFO| Creating a timestamped temporary directory. /shared/aemurphy/H3K4me3_mouse_baker_2019/.caper_tmp/chip/20220209_144626_237277
2022-02-09 14:46:26,254|caper.caper_runner|INFO| Localizing files on work_dir. /shared/aemurphy/H3K4me3_mouse_baker_2019/.caper_tmp/chip/20220209_144626_237277
2022-02-09 14:46:27,189|caper.caper_workflow_opts|INFO| Conda environment name not found in WDL metadata. wdl=/shared/aemurphy/H3K4me3_mouse_baker_2019/chip-seq-pipeline2/chip.wdl
2022-02-09 14:46:27,366|caper.cromwell|INFO| Validating WDL/inputs/imports with Womtool...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/aemurphy/anaconda3/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/aemurphy/anaconda3/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aemurphy/anaconda3/lib/python3.9/site-packages/caper/nb_subproc_thread.py", line 225, in _popen
    stdout_bytes, stderr_bytes = p.communicate()
UnboundLocalError: local variable 'p' referenced before assignment
2022-02-09 14:46:27,374|caper.cromwell|INFO| Passed Womtool validation.
2022-02-09 14:46:27,375|caper.caper_runner|INFO| launching run: wdl=/shared/aemurphy/H3K4me3_mouse_baker_2019/chip-seq-pipeline2/chip.wdl, inputs=/shared/aemurphy/H3K4me3_mouse_baker_2019/germ_BXD100_tr.json, backend_conf=/shared/aemurphy/H3K4me3_mouse_baker_2019/.caper_tmp/chip/20220209_144626_237277/backend.conf
2022-02-09 14:46:27,383|caper.nb_subproc_thread|ERROR| [Errno 2] No such file or directory: 'java'
Traceback (most recent call last):
  File "/home/aemurphy/anaconda3/lib/python3.9/site-packages/caper/nb_subproc_thread.py", line 197, in _popen
    p = Popen(args, stdout=PIPE, stderr=PIPE, cwd=cwd, stdin=stdin)
  File "/home/aemurphy/anaconda3/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/aemurphy/anaconda3/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'java'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/aemurphy/anaconda3/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/aemurphy/anaconda3/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aemurphy/anaconda3/lib/python3.9/site-packages/caper/nb_subproc_thread.py", line 225, in _popen
    stdout_bytes, stderr_bytes = p.communicate()
UnboundLocalError: local variable 'p' referenced before assignment
2022-02-09 14:46:27,385|caper.nb_subproc_thread|INFO| Cromwell stopped but waiting for graceful shutdown...
^C2022-02-09 14:47:03,618|caper.cli|ERROR| 

*** DO NOT CTRL+C MULTIPLE TIMES! ***
*** OR CAPER WILL NOT BE ABLE TO STOP CROMWELL AND RUNNING WORKFLOWS/TASKS ***

Traceback (most recent call last):
  File "/home/aemurphy/anaconda3/lib/python3.9/site-packages/caper/cli.py", line 405, in subcmd_run
    thread.stop(wait=True)
  File "/home/aemurphy/anaconda3/lib/python3.9/site-packages/caper/nb_subproc_thread.py", line 151, in stop
    time.sleep(self._poll_interval)
KeyboardInterrupt
```

I'm not sure where the `UnboundLocalError: local variable 'p' referenced before assignment` issue is coming from?

To note, I have installed the latest version of caper, have created the three conda environments and have downloaded the reference files for mm10 using: `bash chip-seq-pipeline2/scripts/download_genome_data.sh mm10 ./`

This is my `germ_BXD100_tr.json` JSON file:

```
{
    "chip.title" : "germ_BXD100",
    "chip.description" : "H3K4ME1 BXD Mice (single-end)",

    "chip.pipeline_type" : "histone",
    "chip.aligner" : "bowtie2",
    "chip.align_only" : false,
    "chip.true_rep_only" : false,

    "chip.genome_tsv" : "/shared/aemurphy/H3K4me3_mouse_baker_2019/mm10.tsv",

    "chip.paired_end" : false,
    "chip.ctl_paired_end" : false,

    "chip.always_use_pooled_ctl" : true,

    "chip.fastqs_rep1_R1" : ["/shared/aemurphy/H3K4me3_mouse_baker_2019/fastq/SRR7010383_GSM3099729_germ_BXD100_Mus_musculus_ChIP-Seq.fastq.gz"]
}
```

Also to note I'm running on linux.

Thanks!

**Comment by Al-Murphy** [comment]
To note I get the same issue when I try to run this with docker:
```
caper run chip-seq-pipeline2/chip.wdl -i germ_BXD100_tr.json --docker
```
So perhaps the issue is with my json file (of somewhere else?) but I'm not sure what it could be?
