### ISSUE TITLE
cromwell error: java out of bounds

### ISSUE THREAD

**Issue by shinlin77** [ENCODE-DCC/caper#163]
I'm trying to run some of my own data.    I keep running into this problem.  Do you have any suggestions as to the problem?

********** NOTE: Picard's command line syntax is changing.
**********
********** For more information, please see:
********** https://github.com/broadinstitute/picard/wiki/Command-Line-Syntax-Transition-For-Users-(Pre-Transition)
**********
********** The command line looks like this in the new syntax:
**********
**********    CollectGcBiasMetrics -R /oak/stanford/scg/lab_mps/sl/chrombpnet/atac/8a8b155f-837c-4eb6-bd8e-6e3a590132db/call-gc_bias/shard-5/attempt-2/inputs/290321745/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta.gz -I ./Ventricular_Cardiomyocyte.nodup.no_chrM_MT.no_rg.bam -O Ventricular_Cardiomyocyte.nodup.no_chrM_MT.gc.txt -USE_JDK_DEFLATER TRUE -USE_JDK_INFLATER TRUE -VERBOSITY ERROR -QUIET TRUE -ASSUME_SORTED FALSE -CHART Ventricular_Cardiomyocyte.nodup.no_chrM_MT.gcPlot.pdf -S Ventricular_Cardiomyocyte.nodup.no_chrM_MT.gcSummary.txt
**********

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 133338787 out of bounds for length 133275310
        at picard.analysis.GcBiasMetricsCollector.addRead(GcBiasMetricsCollector.java:384)
        at picard.analysis.GcBiasMetricsCollector.access$600(GcBiasMetricsCollector.java:48)
        at picard.analysis.GcBiasMetricsCollector$PerUnitGcBiasMetricsCollector.addReadToGcData(GcBiasMetricsCollector.java:221)
        at picard.analysis.GcBiasMetricsCollector$PerUnitGcBiasMetricsCollector.acceptRecord(GcBiasMetricsCollector.java:155)
        at picard.analysis.GcBiasMetricsCollector$PerUnitGcBiasMetricsCollector.acceptRecord(GcBiasMetricsCollector.java:100)
        at picard.metrics.MultiLevelCollector$AllReadsDistributor.acceptRecord(MultiLevelCollector.java:192)
        at picard.metrics.MultiLevelCollector.acceptRecord(MultiLevelCollector.java:315)
        at picard.analysis.CollectGcBiasMetrics.acceptRead(CollectGcBiasMetrics.java:172)
        at picard.analysis.SinglePassSamProgram.makeItSo(SinglePassSamProgram.java:145)
        at picard.analysis.SinglePassSamProgram.doWork(SinglePassSamProgram.java:84)
        at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:305)
        at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:103)
        at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:113)
Traceback (most recent call last):
  File "/home/sl/.conda/envs/encode-atac-seq-pipeline/bin/encode_task_gc_bias.py", line 143, in <module>

**Comment by shinlin77** [comment]
I think this is due to incompatible genomes (bam versus what caper is using)
