### ISSUE TITLE
Invalid or corrupt jarfile

### ISSUE THREAD

**Issue by lucasrocmoreira** [ENCODE-DCC/caper#164]
I am trying to run the ENCODE ATAC-seq pipeline using the following command: `caper run /seq/vgb/lmoreira/software/atac-seq-pipeline/atac.wdl -i /seq/vgb/lmoreira/flexible_homeostasis/atac_seq/script/camel.json --singularity`, but I keep getting this error:

> 2022-04-04 18:34:05,740|caper.cli|INFO| Cromwell stdout: /home/unix/lmoreira/cromwell.out
> 2022-04-04 18:34:05,780|caper.caper_base|INFO| Creating a timestamped temporary directory. /seq/vgb/lmoreira/software/atac/20220404_183405_744866
> 2022-04-04 18:34:05,780|caper.caper_runner|INFO| Localizing files on work_dir. /seq/vgb/lmoreira/software/atac/20220404_183405_744866
> 2022-04-04 18:34:06,952|caper.caper_workflow_opts|INFO| Singularity image found in WDL metadata. wdl=/seq/vgb/lmoreira/software/atac-seq-pipeline/atac.wdl, s=https://encode-pipeline-singularity-image.s3.us-west-2.amazonaws.com/atac-seq-pipeline_v2.1.3.sif
> 2022-04-04 18:34:06,977|caper.cromwell|INFO| Validating WDL/inputs/imports with Womtool...
> Traceback (most recent call last):
>   File "/home/unix/lmoreira/.local/bin/caper", line 13, in <module>
>     main()
>   File "/home/unix/lmoreira/.local/lib/python3.8/site-packages/caper/cli.py", line 705, in main
>     return runner(parsed_args, nonblocking_server=nonblocking_server)
>   File "/home/unix/lmoreira/.local/lib/python3.8/site-packages/caper/cli.py", line 249, in runner
>     subcmd_run(c, args)
>   File "/home/unix/lmoreira/.local/lib/python3.8/site-packages/caper/cli.py", line 379, in subcmd_run
>     thread = caper_runner.run(
>   File "/home/unix/lmoreira/.local/lib/python3.8/site-packages/caper/caper_runner.py", line 462, in run
>     self._cromwell.validate(wdl=wdl, inputs=inputs, imports=imports)
>   File "/home/unix/lmoreira/.local/lib/python3.8/site-packages/caper/cromwell.py", line 154, in validate
>     raise WomtoolValidationFailed(
> caper.cromwell.WomtoolValidationFailed: RC=1
> STDERR=Error: Invalid or corrupt jarfile /home/unix/lmoreira/.caper/womtool_jar/womtool-65.jar

I have checked the `womtool-65.jar` file and it looks alright. I have also tried to reinstall caper and I still get this error. 

My Java version is:
> java -version
> Picked up _JAVA_OPTIONS: -Xms16M -Xmx2G -XX:ParallelGCThreads=1
> openjdk version "1.7.0_91"
> OpenJDK Runtime Environment (Zulu 7.12.0.3-linux64) (build 1.7.0_91-b15)
> OpenJDK 64-Bit Server VM (Zulu 7.12.0.3-linux64) (build 24.91-b15, mixed mode)

Thank you.

**Comment by lucasrocmoreira** [comment]
It's worth mentioning I'm running this command from an interactive sge session.

**Comment by lucasrocmoreira** [comment]
Just realized my Java version is not >11, so that's the source of the error. I'm closing the issue.
