### ISSUE TITLE
idr threshold

### ISSUE THREAD

**Issue by shinlin77** [ENCODE-DCC/caper#167]
On my own data, I received this error

Exception: File is empty (rep5-pr1_vs_rep5-pr2.idr0.05.narrowPeak.gz). Help: No IDR peaks found. IDR threshold might be too stringent or replicates have very poor concordance.
Traceback (most recent call last):
  File "/home/sl/.conda/envs/encode-atac-seq-pipeline/bin/encode_task_idr.py", line 213, in <module>
    main()
  File "/home/sl/.conda/envs/encode-atac-seq-pipeline/bin/encode_task_idr.py", line 180, in main
    'No IDR peaks found. IDR threshold might be too stringent '
  File "/home/sl/.conda/envs/encode-atac-seq-pipeline/bin/encode_lib_common.py", line 218, in assert_file_not_empty
    raise Exception('File is empty ({}). Help: {}'.format(f, help))
Exception: File is empty (rep5-pr1_vs_rep5-pr2.idr0.05.narrowPeak.gz). Help: No IDR peaks found. IDR threshold might be too stringent or replicates have very poor concordance.

How might I go about changing the IDR threshold?  Alternatively, if there is poor concordance, is there a way to figure out which file is the problem?  Thanks.

**Comment by leepc12** [comment]
Next time please post pipeline's issues on the corresponding pipeline's git repo.

Please find a final (filtered) BAM file and count number of reads in there.
```
$ find -name *.nodup.bam
$ samtools flagstat FOUND_BAM
```

Please refer to this document about IDR threshold. The pipeline is just a wrapper to this software.
https://github.com/kundajelab/idr
