### ISSUE TITLE
Caper run with scatter runs out of memory

### ISSUE THREAD

**Issue by sdwang008** [ENCODE-DCC/caper#201]
Hello! I hope this is the right place to post the issue. 
I am running a whole genome processing pipeline with pretty big BAM files (100GB+ each). The pipeline works with a single sample as input. However, when I run 50 samples at once using the `scatter` syntax, the pipeline gives an error
```
19:25:47,074 cromwell-system-akka.dispatchers.service-dispatcher-93 ERROR - WriteMetadataActor Failed to properly process data
java.sql.SQLException: java.lang.OutOfMemoryError: Java heap space
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.addBatch(Unknown Source)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.addBatch(HikariProxyPreparedStatement.java)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$19(JdbcActionComponent.scala:540)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$19$adapted(JdbcActionComponent.scala:538)
	at scala.collection.immutable.VectorStatics$.foreachRec(Vector.scala:1856)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1862)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$18(JdbcActionComponent.scala:538)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:427)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:422)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:491)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:511)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:536)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
	at slick.dbio.DBIOAction$$anon$1.$anonfun$run$1(DBIOAction.scala:186)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
	at slick.dbio.DBIOAction$$anon$1.run(DBIOAction.scala:186)
	at slick.dbio.DBIOAction$$anon$1.run(DBIOAction.scala:183)
	at slick.dbio.SynchronousDatabaseAction$$anon$7.run(DBIOAction.scala:486)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.hsqldb.HsqlException: java.lang.OutOfMemoryError: Java heap space
	at org.hsqldb.error.Error.error(Unknown Source)
	at org.hsqldb.SessionData.allocateLobForResult(Unknown Source)
	at org.hsqldb.Session.allocateResultLob(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.performPreExecute(Unknown Source)
	... 24 common frames omitted
Caused by: java.lang.OutOfMemoryError: Java heap space
	at org.hsqldb.persist.LobStoreMem.setBlockBytes(Unknown Source)
	at org.hsqldb.persist.LobManager.setBytesISNormal(Unknown Source)
	at org.hsqldb.persist.LobManager.setBytesIS(Unknown Source)
	at org.hsqldb.persist.LobManager.setCharsForNewClob(Unknown Source)
	at org.hsqldb.SessionData.allocateLobForResult(Unknown Source)
	at org.hsqldb.Session.allocateResultLob(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.performPreExecute(Unknown Source)
	at org.hsqldb.jdbc.JDBCPreparedStatement.addBatch(Unknown Source)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.addBatch(HikariProxyPreparedStatement.java)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$19(JdbcActionComponent.scala:540)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$19$adapted(JdbcActionComponent.scala:538)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction$$Lambda$3135/0x00000008016e2e10.apply(Unknown Source)
	at scala.collection.immutable.VectorStatics$.foreachRec(Vector.scala:1856)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1862)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.$anonfun$run$18(JdbcActionComponent.scala:538)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction$$Lambda$3134/0x00000008016e2a58.apply(Unknown Source)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:427)
	at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:422)
	at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:491)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:511)
	at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$MultiInsertAction.run(JdbcActionComponent.scala:536)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
	at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
	at slick.dbio.DBIOAction$$anon$1.$anonfun$run$1(DBIOAction.scala:186)
	at slick.dbio.DBIOAction$$anon$1$$Lambda$3140/0x00000008016e81f8.apply(Unknown Source)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
	at slick.dbio.DBIOAction$$anon$1.run(DBIOAction.scala:186)
	at slick.dbio.DBIOAction$$anon$1.run(DBIOAction.scala:183)
	at slick.dbio.SynchronousDatabaseAction$$anon$7.run(DBIOAction.scala:486)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
	at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
``` 
This to me looks like the leader job ran out of memory? My setup is that, on top of the original pipeline that takes a single input, I wrote another script just to `scatter` call the original pipeline. I then call `caper run` on this scatter script. Code is like this:
```
scatter (idx in range(length(input_bams))) {
        call pipeline.WholeGenomeReprocessing {
            input:
                input_bam = input_bams[idx],
                sample_name = sample_names[idx],
                base_file_name = base_file_names[idx]
        }
    }
```
Should I structure this in a different way, or is this error due to some kind of system/backend setting? I have tried the parameter `java-heap-run` for `caper run` and set it to 32G but did not make a difference. Could you please help me diagnose and solve this issue? Thank you!

**Comment by leepc12** [comment]
This looks like an `in-memory` HSQLDB issue. Can you add `--db file --file-db /YOUR/HOME/temp/dir/caper_hsqldb` to `caper run` and try again?
`/YOUR/HOME/temp/dir/caper_hsqldb` will be a prefix for temporary files of Cromwell's file based metadata database. Can use any temporary directory.

**Comment by sdwang008** [comment]
> This looks like an `in-memory` HSQLDB issue. Can you add `--db file --file-db /YOUR/HOME/temp/dir/caper_hsqldb` to `caper run` and try again? `/YOUR/HOME/temp/dir/caper_hsqldb` will be a prefix for temporary files of Cromwell's file based metadata database. Can use any temporary directory.

Thanks for your reply! It is indeed that issue. We figured out an alternative using `caper server` while running a mysql server, writing the metadata database to the mysql server.
