### ISSUE TITLE
caper cannot find singularity command if SINGULARITY_CACHEDIR environment variable does not exist

### ISSUE THREAD

**Issue by ro-joshi** [ENCODE-DCC/caper#26]
I'm running caper with the slurm backend. When SINGULARITY_CACHEDIR variable is unset, I get the following error when running `caper submit --singularity ...` within a bash script:

```
Traceback (most recent call last):
  File "/N/users/rojoshi/anaconda3/envs/encode-atac-seq-pipeline/bin/caper", line 13, in <module>
    main()
  File "/N/users/rojoshi/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper.py", line 1238, in main
    c.submit()
  File "/N/users/rojoshi/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper.py", line 382, in submit
    input_file, tmp_dir)
  File "/N/users/rojoshi/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper.py", line 745, in __create_workflow_opts_json_file
    self.__build_singularity_image(singularity)
  File "/N/users/rojoshi/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper.py", line 1042, in __build_singularity_image
    return check_call(cmd, env=env)
  File "/N/users/rojoshi/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/subprocess.py", line 323, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/N/users/rojoshi/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/subprocess.py", line 304, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/N/users/rojoshi/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/N/users/rojoshi/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'singularity': 'singularity'
```

If I execute the script that calls `caper submit` with `SINGULARITY_CACHEDIR=<path>/singularity_cachedir/ script.sh`, the command executes successfully.

I think these lines in caper.py:__build_singularity_image:1037-1039 are the problem:
```
            if self._singularity_cachedir is not None \
                    and 'SINGULARITY_CACHEDIR' not in os.environ:
                env = {'SINGULARITY_CACHEDIR': self._singularity_cachedir}
```
Likely could be fixed by:
```
            if self._singularity_cachedir is not None \
                    and 'SINGULARITY_CACHEDIR' not in os.environ:
                env=os.environ.copy()
                env['SINGULARITY_CACHEDIR'] = self._singularity_cachedir
```

**Comment by leepc12** [comment]
Thanks, this will be fixed in the next release.
