### ISSUE TITLE
List module raises KeyError on Subworkflows

### ISSUE THREAD

**Issue by alexwaldrop** [ENCODE-DCC/caper#38]
Just started using the tool and am pleased by the promise to have something I can use to coordinate runs across projects.

I'm using caper v0.6.2 and have noticed the list command doesn't handle the JSON structure for subworkflows. Because subworkflows don't have a 'submission' key returned by the API, it raises a KeyError. Are there any plans to handle subworkflows or at least skip them in the future?

Log:
Traceback (most recent call last):
  File "/Users/awaldrop/anaconda3/bin/caper", line 13, in <module>
    main()
  File "/Users/awaldrop/anaconda3/lib/python3.6/site-packages/caper/caper.py", line 1274, in main
    c.list()
  File "/Users/awaldrop/anaconda3/lib/python3.6/site-packages/caper/caper.py", line 482, in list
    submission = w['submission']
KeyError: 'submission'

**Comment by leepc12** [comment]
Can you edit `/Users/awaldrop/anaconda3/lib/python3.6/site-packages/caper/caper.py` and just remove that line 482 `submission = w['submission']`?

This will be fixed in the next release.
