### ISSUE TITLE
caper Cannot Connect to Server

### ISSUE THREAD

**Issue by imk1** [ENCODE-DCC/caper#40]
I am using caper to submit the latest ATAC-seq pipeline, and I am getting the following error:
[CaperURI] copying from url to local, src: https://github.com/broadinstitute/cromwell/releases/download/47/cromwell-47.jar
Traceback (most recent call last):
  File "/home/ikaplow/miniconda3/envs/encode-atac-seq-pipeline/bin/caper", line 13, in <module>
    main()
  File "/home/ikaplow/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper.py", line 1267, in main
    c.run()
  File "/home/ikaplow/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper.py", line 213, in run
    self.__download_cromwell_jar(), 'run',
  File "/home/ikaplow/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper.py", line 591, in __download_cromwell_jar
    return cu.copy(target_uri=path)
  File "/home/ikaplow/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper_uri.py", line 445, in copy
    ignored_http_err=(416,))
  File "/home/ikaplow/miniconda3/envs/encode-atac-seq-pipeline/lib/python3.7/site-packages/caper/caper_uri.py", line 988, in __curl_auto_auth
    rc, http_err, stderr))
Exception: cURL RC: 7, HTTP_ERR: 0, STDERR:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Couldn't connect to server

I am running caper from a login node.  Do you know how I might be able to solve this problem?  Thanks!

**Comment by leepc12** [comment]
Git file server for the cromwell JAR looks down.
Check if you have already downloaded `~/.caper/cromwell_jar/cromwell-47.jar`. If so,
Add the following to your `~/.caper/default.conf`.
```
cromwell=~/.caper/cromwell_jar/cromwell-47.jar
womtool=~/.caper/womtool_jar/womtool-47.jar
```

**Comment by imk1** [comment]
I think that worked!  Thank you so much!
