### ISSUE TITLE
~/.caper/default.conf file not created after invoking caper init 

### ISSUE THREAD

**Issue by rw4917** [ENCODE-DCC/caper#77]
Hi I am trying to run your pipeline on the cluster at my university, Imperial College London which uses pbs cluster . after running the `caper init`, or  `caper init pbs `commands, the ~/.caper/default.conf file doesn't seem to be created , and as a consequence I get the following error: 

```
Traceback (most recent call last):
  File "/rds/general/user/rw4917/home/anaconda3/envs/encode-atac-seq-pipeline/bin/caper", line 13, in <module>
    main()
  File "/rds/general/user/rw4917/home/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.6/site-packages/caper/cli.py", line 500, in main
    init_caper_conf(parsed_args.conf, parsed_args.platform)
  File "/rds/general/user/rw4917/home/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.6/site-packages/caper/caper_init.py", line 180, in init_caper_conf
    with open(conf_file, 'w') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/rds/general/user/rw4917/home/.caper/default.conf'
```

I tried manually creating a blank ~/.caper/default.conf file but then get 

```
Traceback (most recent call last):
  File "/rds/general/user/rw4917/home/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.6/configparser.py", line 846, in items
    d.update(self._sections[section])
KeyError: 'defaults'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/rds/general/user/rw4917/home/anaconda3/envs/encode-atac-seq-pipeline/bin/caper", line 13, in <module>
    main()
  File "/rds/general/user/rw4917/home/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.6/site-packages/caper/cli.py", line 481, in main
    parser, _ = get_parser_and_defaults()
  File "/rds/general/user/rw4917/home/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.6/site-packages/caper/caper_args.py", line 699, in get_parser_and_defaults
    conf_key_map=CAPER_1_0_0_PARAM_KEY_NAME_CHANGE,
  File "/rds/general/user/rw4917/home/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.6/site-packages/caper/arg_tool.py", line 120, in update_parsers_defaults_with_conf
    no_strip_quote=no_strip_quote,
  File "/rds/general/user/rw4917/home/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.6/site-packages/caper/arg_tool.py", line 47, in read_from_conf
    d_ = dict(config.items(conf_section))
  File "/rds/general/user/rw4917/home/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.6/configparser.py", line 849, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'defaults'
```
Sorry if this is a trivial fix I am quite new to submitting jobs on clusters
Thanks in advance !

**Comment by leepc12** [comment]
What is your Caper version? 
```
$ caper -v
```

**Comment by rw4917** [comment]
I get also an error by running `caper -v `
```
$(encode-atac-seq-pipeline) -bash-4.2$ caper -v
Traceback (most recent call last):
  File "/rds/general/user/rw4917/home/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.6/configparser.py", line 846, in items
    d.update(self._sections[section])
KeyError: 'defaults'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/rds/general/user/rw4917/home/anaconda3/envs/encode-atac-seq-pipeline/bin/caper", line 13, in <module>
    main()
  File "/rds/general/user/rw4917/home/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.6/site-packages/caper/cli.py", line 481, in main
    parser, _ = get_parser_and_defaults()
  File "/rds/general/user/rw4917/home/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.6/site-packages/caper/caper_args.py", line 699, in get_parser_and_defaults
    conf_key_map=CAPER_1_0_0_PARAM_KEY_NAME_CHANGE,
  File "/rds/general/user/rw4917/home/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.6/site-packages/caper/arg_tool.py", line 120, in update_parsers_defaults_with_conf
    no_strip_quote=no_strip_quote,
  File "/rds/general/user/rw4917/home/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.6/site-packages/caper/arg_tool.py", line 47, in read_from_conf
    d_ = dict(config.items(conf_section))
  File "/rds/general/user/rw4917/home/anaconda3/envs/encode-atac-seq-pipeline/lib/python3.6/configparser.py", line 849, in items
    raise NoSectionError(section)
configparser.NoSectionError: No section: 'defaults'
```

However, when I run `pip freeze `I get listed `caper==1.0.0`

**Comment by leepc12** [comment]
Can you try a clean install for Caper?
```
$ pip uninstall caper
$ pip install caper
```

**Comment by rw4917** [comment]
I already tried that a couple of times. Should I maybe look at downloading with git instead ?

**Comment by rw4917** [comment]
I already tried that a couple of times, but still face the same problem.I ll try once more.  Should I also maybe look at downloading with git instead ?

**Comment by leepc12** [comment]
You are in atac-seq pipeline's Conda environment. Can you try outside of it? If that works, let's discuss more to make it work inside of it.

**Comment by rw4917** [comment]
I have tried inside and outside of the Conda environment and get the same error. I also now tried cloning the file from git but got same error. Any other suggestion ? Thanks again for your help

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by leepc12** [comment]
Can you try `pip install configparser --upgrade`?

**Comment by BKLi** [comment]
Yeah I ran into the same error. I tried installing inside and outside of the environment, installing under python 3.6/3.7/3.8, installing with git instead of pip, but all failed with the same error. I also did ```pip install configparser --upgrade``` but that didn't work either, unfortunately.

**Comment by leepc12** [comment]
@rw4917: Can you try this on your session?

```
$ ls -l /rds/general/user/rw4917/home/.caper
$ touch /rds/general/user/rw4917/home/.caper/default.conf
$ ls -l /rds/general/user/rw4917/home/.caper
```

**Comment by Monster2060** [comment]
Hey, 

I have the same issue when I try I tried ``` caper init local``` and received 
``` Traceback (most recent call last):
  File "/usr/local/bin/caper", line 13, in <module>
    main()
  File "/usr/local/lib/python3.8/site-packages/caper/cli.py", line 589, in main
    init_caper_conf(parsed_args.conf, parsed_args.platform)
  File "/usr/local/lib/python3.8/site-packages/caper/caper_init.py", line 180, in init_caper_conf
    with open(conf_file, 'w') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/j/.caper/default.conf' ```

**Comment by leepc12** [comment]
This will be fixed in the next release.
Until then, run the following command to make a directory for the conf file and delete existing one:
```bash
$ mkdir ~/.caper/
$ rm -f ~/.caper/default.conf
```

**Comment by Monster2060** [comment]
That fixes it thanks!

**Comment by coffeeCowLu** [comment]
> This will be fixed in the next release.
> Until then, run the following command to make a directory for the conf file and delete existing one:
> 
> ```shell
> $ mkdir -p ~/.caper/
> $ rm -f ~/.caper/default.conf
> ```

thanks very much!!!
